---
# Repo links for mssql
mssql_server_repo:  "https://packages.microsoft.com/config/rhel/7/mssql-server-2017.repo -o /etc/yum.repos.d/mssql-server-2017.repo" 
mssql_prod_repo:  "https://packages.microsoft.com/config/rhel/7/prod.repo -o /etc/yum.repos.d/msprod.repo"

# Remove old ODBC Packages
unixODBC: ['unixODBC-utf16', 'unixODBC-utf16-devel']

# All Required mssql server packages
mssql_server_version: 'mssql-server-14.0.1*'
mssql_server_packages: ['unixODBC-devel','{{mssql_server_version}}','python-pip','python-devel']


# Database Server Configuratin
server_type: 'Developer'

